mixmicro:
  spring:
    web:
    response-wrap-advice: false
spring:
  # mvc
  mvc:
    # 404 直接抛异常
    throw-exception-if-no-handler-found: true
    resources.add-mappings: false
    static-path-pattern: /**
    async:
      request-timeout: 60000 # 设置接口超时时间60s
  jackson:
    default-property-inclusion: non_null
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:p6spy:mysql://10.10.10.100:3306/paperless?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useAffectedRows=true&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  redis:
    host: 10.10.10.100
    port: 6379
    password: tc!@#123redis
  # 缓存
  cache:
    redis:
      time-to-live: 20
  cloud:
    # nacos-配置
    nacos:
      config:
        # 是否开启配置中心，默认true
        enabled: true
        server-addr: 10.10.10.100:8848
        file-extension: yaml
        encode: UTF-8
        # 命名空间的id
        namespace: 59debcf2-4a92-4c9c-b164-c003dd1360c2
        group: PAPERLESS
        shared-configs[0]:
          dataId: common-${spring.profiles.active}.yaml
          group:  ${spring.cloud.nacos.config.group}
          refresh: true
      # 注册发现中心
      discovery:
        # 是否开启注册中心，默认true
        enabled: true
        group: ${spring.cloud.nacos.config.group}
        # 默认应用名
        service: ${spring.application.name}
        server-addr: ${spring.cloud.nacos.config.server-addr}
        namespace: ${spring.cloud.nacos.config.namespace}
  # thymeleaf
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML
    cache: false
    servlet:
      content-type: text/html
  # 静态资源映射
  resources:
    static-locations: classpath:/static/

  # activemq
  activemq:
    broker-url: tcp://10.10.10.100:61616
    password: admin
    user: admin
    queue-name-empty: tc.queue.emptyContainer
    queue-name-full: tc.queue.fullContainer
    queue-name-ship-use-location: tc.queue.shipUseLocationRecord
    queue-name: tc.queue-name
    topic-name: tc.http.active.topic
    pool:
      enabled: true
      max-connections: 100
    packages:
      #注意 对象传输需开启包白名单 否则会报错- -
      trust-all: true
    in-memory: true
    # 自定义queue名称
    paperless-life-cycle-queue-name: paperless-life-cycle-queue
    # 自定义topic名称
    paperless-life-cycle-topic-name: paperless-life-cycle-topic
  jms:
    # 开启发布订阅模式
    pub-sub-domain: true


swagger:
  base-package: com.yunlsp.tcg
  contact:
    email: developer@yunlsp.com
    name: YunLSP+ Developer
    url: http://developer.yunlsp.com
  title: fleet module's apis
  version: ${project.version}

ribbon:
  eager-load:
    enabled: true #开启饥饿加载
    clients: fleet,carrier #为哪些服务的名称开启饥饿加载,多个用逗号分隔
  MaxAutoRetries: 1  #最大重试次数，当注册中心中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetriesNextServer: 1  #切换实例的重试次数
  OkToRetryOnAllOperations: false  #对所有操作请求都进行重试，如果是get则可以，如果是post，put等操作没有实现幂等的情况下是很危险的,所以设置为false
  ConnectTimeout: 10000 #请求连接的超时时间
  ReadTimeout: 20000 #请求处理的超时时间

# feign 配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  client:
    config:
      default:
        # 连接超时时间5s
        connectTimeout: 5000
        # 接口超时时间60s
        readTimeout: 60000
  # 开启feign的熔断功能
  sentinel:
    enabled: true

management:
  health:
    #邮箱
    mail:
      enabled: false
  endpoints:
    health:
      show-details: always
    web:
      exposure:
        include: '*'

  #MyBatisPlus
  #文档： https://mp.baomidou.com/config/#%E5%9F%BA%E6%9C%AC%E9%85%8D%E7%BD%AE
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
  global-config:
    banner: false # 关闭打印mybatis-plus的LOGO
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

tc:
  adapter:
    permissions-url: http://adpttest.tceport.com.cn/tcg/httpApi/verifyPermissions
    decode-url: http://adpttest.tceport.com.cn/tcg/httpApi/decode
    encrypt-url: http://adpttest.tceport.com.cn/tcg/httpApi/encrypt
    send-code: TCEPORT_IN_S0006
    secret-key: 9b4066c1-9949-11e9-b3bb-0242ac110002
    business-url: http://adpttest.tceport.com.cn/tcg/httpApi/request

getUrl: http://218.4.219.82:10002/base-account-service/v1/account/getAccountListById/

# 鉴权
auth:
  # 不需要鉴权的路径
  ignores:
    - "/"
    - "/templates/**"
    - "/imgs/**"
    - "*.css"
    - "*.js"
    - "*.gif"
    - "*.jpg"
    - "*.png"
    - "*.ico"
    - "/favicon.ico"
    - "/actuator/**"
    - "/swagger-ui.html"
    - "/doc.html"
    - "/swagger-resources/**"
    - "/baseMessage/**"
    - "/service-worker.js"
    - "/v2/**"
    - "/webjars/**"

jwt:
  token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJhdXRoIiwiYWNjb3VudF9pZCI6IjEyNjk5MDU3MDQ4NTI5Mzg3NTMiLCJpc3MiOiJjaHVhbmRhaTEiLCJyZWZyZXNoIjoxNTk2ODAxNDk2LCJleHAiOjE1OTY4MDIwOTZ9.J2K1sXYJN7yAXNjzhP
